import React, { useMemo, useState } from "react";
import { Button, Checkbox, Dialog, DialogContent, FormControlLabel, FormGroup, IconButton, Stack, Tooltip, Typography } from "@mui/material";
import {
    BiosampleTable,
    EncodeBiosample,
    GridRowParams,
    isAutogeneratedRow,
    useEncodeBiosampleData,
    useGridApiRef,
} from "@weng-lab/ui-components";
import { GeneLinkingMethod } from "../../../../types";
import TissueList from "./TissueList";
import { CancelRounded } from "@mui/icons-material";

interface BiosampleSelectProps {
    open: boolean;
    onClose: () => void;
    assembly: "GRCh38" | "mm10";
    handleLinkageBiosampleSubmit: (method: GeneLinkingMethod, cellType: EncodeBiosample, include: boolean) => void
    extraRows: EncodeBiosample[];
    method: GeneLinkingMethod;
}

export const LinkageBiosampleModal: React.FC<BiosampleSelectProps> = ({
    assembly,
    open,
    handleLinkageBiosampleSubmit,
    onClose,
    extraRows,
    method,
}) => {
    const [include, setInclude] = useState(false);
    const [selected, setSelected] = useState<EncodeBiosample | null>(null);

    const {
        data: encodeSamples,
        loading: encodeLoading,
        error: encodeError,
    } = useEncodeBiosampleData({ assembly: "GRCh38", skip: method === "eQTLs" });

    //Custom rows logic to include extraRows (computational cell types) and only show encode samples with RNASeq data
    const rows: EncodeBiosample[] = useMemo(() => {
        if (encodeLoading || encodeError || !encodeSamples) {
            return [];
        }
        const encodeWithRnaSeq = encodeSamples.filter(
            (b) => b.rna_seq_tracks.length > 0
        );

        if (!extraRows || extraRows.length === 0) {
            return [...encodeWithRnaSeq].sort((a, b) =>
                a.ontology.localeCompare(b.ontology)
            );
        }

        const extraNames = new Set(extraRows.map((e) => e.name));

        const matchingEncodeSamples = encodeWithRnaSeq.filter((b) =>
            extraNames.has(b.name)
        );

        const encodeNames = new Set(encodeWithRnaSeq.map((b) => b.name));

        const newExtraRows = extraRows.filter(
            (e) => !encodeNames.has(e.name)
        );

        return [...matchingEncodeSamples, ...newExtraRows].sort((a, b) =>
            a.ontology.localeCompare(b.ontology)
        );
    }, [encodeError, encodeLoading, encodeSamples, extraRows]);

    const handleSelectionChange = (samples: EncodeBiosample[]) => {
        setSelected(samples[0]); // will only be length one since we specify disableMultipleRowSelection, and are disabling grouped row selection
    };

    const handleSubmit = () => {
        handleLinkageBiosampleSubmit(method, selected, include)
        setSelected(null);
        setInclude(false);
    }

    const apiRef = useGridApiRef();

    // used to apply cursor: "pointer" to clickable leaf nodes
    const getRowClassName = (params: GridRowParams) => {
        if (!isAutogeneratedRow(params.row)) {
            return "is-leaf-row";
        }
        return "";
    };

    return (
        <Dialog open={open} onClose={onClose} maxWidth="sm" fullWidth keepMounted>
            <DialogContent>
                <Typography variant="h6" gutterBottom>
                    Linkage Method: {method}
                </Typography>
                {selected && (
                    <Stack
                        minWidth={"350px"}
                        direction="row"
                        alignItems={"center"}
                        borderRadius={1}
                        justifyContent={"space-between"}
                        sx={{ backgroundColor: theme => theme.palette.secondary.main }}
                        width={"fit-content"}
                        paddingX={1}
                    >
                        <Typography><b>Selected: </b>{selected.displayname}</Typography>
                        <IconButton onClick={() => setSelected(null)}>
                            <CancelRounded />
                        </IconButton>
                    </Stack>
                )}
                {method !== "eQTLs" ? (
                    <BiosampleTable
                        apiRef={apiRef}
                        rows={rows}
                        loading={encodeLoading}
                        error={encodeError}
                        label={"Select a Biosample"}
                        assembly={assembly}
                        disableMultipleRowSelection
                        isRowSelectable={(params) => !isAutogeneratedRow(params.row)}
                        disableRowSelectionOnClick={false}
                        onSelectionChange={handleSelectionChange}
                        rowSelectionModel={{ type: "include", ids: new Set(selected ? [selected?.name] : []) }}
                        divHeight={{ maxHeight: 650 }}
                        getRowClassName={getRowClassName}
                        sx={{ "& .is-leaf-row:hover": { cursor: "pointer" } }} // used to apply cursor: "pointer" to clickable leaf nodes
                        //temp, remove when enabled in theme
                        disableRowGrouping={false}
                    />
                ) : (
                    <TissueList
                        onSelect={(t) =>
                            setSelected({
                                name: t,
                                ontology: t,
                                displayname: t,
                                lifeStage: "other",
                                sampleType: "other",
                                dnase_experiment_accession: null,
                                h3k4me3_experiment_accession: null,
                                h3k27ac_experiment_accession: null,
                                ctcf_experiment_accession: null,
                                atac_experiment_accession: null,
                                dnase_file_accession: null,
                                h3k4me3_file_accession: null,
                                h3k27ac_file_accession: null,
                                ctcf_file_accession: null,
                                atac_file_accession: null,
                                rna_seq_tracks: [],
                            })
                        }
                        selected={selected}
                    />
                )}
                <Stack width="100%" direction={"row"} spacing={1} alignItems={"center"} justifyContent={"flex-end"}>
                    <FormGroup>
                        <Tooltip
                            title={
                                !selected || selected.rna_seq_tracks.length === 0
                                    ? "Selected Biosample does not have RNASeq Data and can not be used in Gene Expression Calculation"
                                    : ""
                            }
                        >
                            <span>
                                <FormControlLabel
                                    control={<Checkbox />}
                                    label="Include in Gene Expression Calculation"
                                    onChange={setInclude.bind(this, !include)}
                                    checked={(selected?.rna_seq_tracks.length === 0) ? false : include}
                                    disabled={!selected || selected.rna_seq_tracks.length === 0}
                                />
                            </span>
                        </Tooltip>
                    </FormGroup>
                    <Button
                        variant="contained"
                        onClick={() => handleSubmit()}
                    >
                        Submit
                    </Button>
                </Stack>
            </DialogContent>
        </Dialog>
    );
};
